// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf/wpList.proto

package protobuf.data.wbList;

public final class WbListData {
  private WbListData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WbOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string type = 2;
    boolean hasType();
    String getType();
  }
  public static final class Wb extends
      com.google.protobuf.GeneratedMessage
      implements WbOrBuilder {
    // Use Wb.newBuilder() to construct.
    private Wb(Builder builder) {
      super(builder);
    }
    private Wb(boolean noInit) {}
    
    private static final Wb defaultInstance;
    public static Wb getDefaultInstance() {
      return defaultInstance;
    }
    
    public Wb getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      type_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.data.wbList.WbListData.Wb parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.wbList.WbListData.Wb parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.Wb parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.data.wbList.WbListData.Wb prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.data.wbList.WbListData.WbOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_fieldAccessorTable;
      }
      
      // Construct using wbList.data.protobuf.WbListData.Wb.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.data.wbList.WbListData.Wb.getDescriptor();
      }
      
      public protobuf.data.wbList.WbListData.Wb getDefaultInstanceForType() {
        return protobuf.data.wbList.WbListData.Wb.getDefaultInstance();
      }
      
      public protobuf.data.wbList.WbListData.Wb build() {
        protobuf.data.wbList.WbListData.Wb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.data.wbList.WbListData.Wb buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.data.wbList.WbListData.Wb result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.data.wbList.WbListData.Wb buildPartial() {
        protobuf.data.wbList.WbListData.Wb result = new protobuf.data.wbList.WbListData.Wb(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.data.wbList.WbListData.Wb) {
          return mergeFrom((protobuf.data.wbList.WbListData.Wb)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.data.wbList.WbListData.Wb other) {
        if (other == protobuf.data.wbList.WbListData.Wb.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              type_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string type = 2;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.Wb)
    }
    
    static {
      defaultInstance = new Wb(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.Wb)
  }
  
  public interface WbListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Wb wb = 1;
    java.util.List<protobuf.data.wbList.WbListData.Wb> 
        getWbList();
    protobuf.data.wbList.WbListData.Wb getWb(int index);
    int getWbCount();
    java.util.List<? extends protobuf.data.wbList.WbListData.WbOrBuilder> 
        getWbOrBuilderList();
    protobuf.data.wbList.WbListData.WbOrBuilder getWbOrBuilder(
        int index);
  }
  public static final class WbList extends
      com.google.protobuf.GeneratedMessage
      implements WbListOrBuilder {
    // Use WbList.newBuilder() to construct.
    private WbList(Builder builder) {
      super(builder);
    }
    private WbList(boolean noInit) {}
    
    private static final WbList defaultInstance;
    public static WbList getDefaultInstance() {
      return defaultInstance;
    }
    
    public WbList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_fieldAccessorTable;
    }
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Wb wb = 1;
    public static final int WB_FIELD_NUMBER = 1;
    private java.util.List<protobuf.data.wbList.WbListData.Wb> wb_;
    public java.util.List<protobuf.data.wbList.WbListData.Wb> getWbList() {
      return wb_;
    }
    public java.util.List<? extends protobuf.data.wbList.WbListData.WbOrBuilder> 
        getWbOrBuilderList() {
      return wb_;
    }
    public int getWbCount() {
      return wb_.size();
    }
    public protobuf.data.wbList.WbListData.Wb getWb(int index) {
      return wb_.get(index);
    }
    public protobuf.data.wbList.WbListData.WbOrBuilder getWbOrBuilder(
        int index) {
      return wb_.get(index);
    }
    
    private void initFields() {
      wb_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getWbCount(); i++) {
        if (!getWb(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < wb_.size(); i++) {
        output.writeMessage(1, wb_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < wb_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, wb_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.data.wbList.WbListData.WbList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.wbList.WbListData.WbList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.wbList.WbListData.WbList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.data.wbList.WbListData.WbList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.data.wbList.WbListData.WbListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.data.wbList.WbListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_fieldAccessorTable;
      }
      
      // Construct using wbList.data.protobuf.WbListData.WbList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWbFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (wbBuilder_ == null) {
          wb_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          wbBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.data.wbList.WbListData.WbList.getDescriptor();
      }
      
      public protobuf.data.wbList.WbListData.WbList getDefaultInstanceForType() {
        return protobuf.data.wbList.WbListData.WbList.getDefaultInstance();
      }
      
      public protobuf.data.wbList.WbListData.WbList build() {
        protobuf.data.wbList.WbListData.WbList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.data.wbList.WbListData.WbList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.data.wbList.WbListData.WbList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.data.wbList.WbListData.WbList buildPartial() {
        protobuf.data.wbList.WbListData.WbList result = new protobuf.data.wbList.WbListData.WbList(this);
        int from_bitField0_ = bitField0_;
        if (wbBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            wb_ = java.util.Collections.unmodifiableList(wb_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.wb_ = wb_;
        } else {
          result.wb_ = wbBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.data.wbList.WbListData.WbList) {
          return mergeFrom((protobuf.data.wbList.WbListData.WbList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.data.wbList.WbListData.WbList other) {
        if (other == protobuf.data.wbList.WbListData.WbList.getDefaultInstance()) return this;
        if (wbBuilder_ == null) {
          if (!other.wb_.isEmpty()) {
            if (wb_.isEmpty()) {
              wb_ = other.wb_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWbIsMutable();
              wb_.addAll(other.wb_);
            }
            onChanged();
          }
        } else {
          if (!other.wb_.isEmpty()) {
            if (wbBuilder_.isEmpty()) {
              wbBuilder_.dispose();
              wbBuilder_ = null;
              wb_ = other.wb_;
              bitField0_ = (bitField0_ & ~0x00000001);
              wbBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWbFieldBuilder() : null;
            } else {
              wbBuilder_.addAllMessages(other.wb_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getWbCount(); i++) {
          if (!getWb(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              protobuf.data.wbList.WbListData.Wb.Builder subBuilder = protobuf.data.wbList.WbListData.Wb.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addWb(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.oxseed.saas.archive.ocr.servlet.data.Wb wb = 1;
      private java.util.List<protobuf.data.wbList.WbListData.Wb> wb_ =
        java.util.Collections.emptyList();
      private void ensureWbIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          wb_ = new java.util.ArrayList<protobuf.data.wbList.WbListData.Wb>(wb_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.data.wbList.WbListData.Wb, protobuf.data.wbList.WbListData.Wb.Builder, protobuf.data.wbList.WbListData.WbOrBuilder> wbBuilder_;
      
      public java.util.List<protobuf.data.wbList.WbListData.Wb> getWbList() {
        if (wbBuilder_ == null) {
          return java.util.Collections.unmodifiableList(wb_);
        } else {
          return wbBuilder_.getMessageList();
        }
      }
      public int getWbCount() {
        if (wbBuilder_ == null) {
          return wb_.size();
        } else {
          return wbBuilder_.getCount();
        }
      }
      public protobuf.data.wbList.WbListData.Wb getWb(int index) {
        if (wbBuilder_ == null) {
          return wb_.get(index);
        } else {
          return wbBuilder_.getMessage(index);
        }
      }
      public Builder setWb(
          int index, protobuf.data.wbList.WbListData.Wb value) {
        if (wbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWbIsMutable();
          wb_.set(index, value);
          onChanged();
        } else {
          wbBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setWb(
          int index, protobuf.data.wbList.WbListData.Wb.Builder builderForValue) {
        if (wbBuilder_ == null) {
          ensureWbIsMutable();
          wb_.set(index, builderForValue.build());
          onChanged();
        } else {
          wbBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addWb(protobuf.data.wbList.WbListData.Wb value) {
        if (wbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWbIsMutable();
          wb_.add(value);
          onChanged();
        } else {
          wbBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addWb(
          int index, protobuf.data.wbList.WbListData.Wb value) {
        if (wbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWbIsMutable();
          wb_.add(index, value);
          onChanged();
        } else {
          wbBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addWb(
          protobuf.data.wbList.WbListData.Wb.Builder builderForValue) {
        if (wbBuilder_ == null) {
          ensureWbIsMutable();
          wb_.add(builderForValue.build());
          onChanged();
        } else {
          wbBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addWb(
          int index, protobuf.data.wbList.WbListData.Wb.Builder builderForValue) {
        if (wbBuilder_ == null) {
          ensureWbIsMutable();
          wb_.add(index, builderForValue.build());
          onChanged();
        } else {
          wbBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllWb(
          java.lang.Iterable<? extends protobuf.data.wbList.WbListData.Wb> values) {
        if (wbBuilder_ == null) {
          ensureWbIsMutable();
          super.addAll(values, wb_);
          onChanged();
        } else {
          wbBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearWb() {
        if (wbBuilder_ == null) {
          wb_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          wbBuilder_.clear();
        }
        return this;
      }
      public Builder removeWb(int index) {
        if (wbBuilder_ == null) {
          ensureWbIsMutable();
          wb_.remove(index);
          onChanged();
        } else {
          wbBuilder_.remove(index);
        }
        return this;
      }
      public protobuf.data.wbList.WbListData.Wb.Builder getWbBuilder(
          int index) {
        return getWbFieldBuilder().getBuilder(index);
      }
      public protobuf.data.wbList.WbListData.WbOrBuilder getWbOrBuilder(
          int index) {
        if (wbBuilder_ == null) {
          return wb_.get(index);  } else {
          return wbBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf.data.wbList.WbListData.WbOrBuilder> 
           getWbOrBuilderList() {
        if (wbBuilder_ != null) {
          return wbBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(wb_);
        }
      }
      public protobuf.data.wbList.WbListData.Wb.Builder addWbBuilder() {
        return getWbFieldBuilder().addBuilder(
            protobuf.data.wbList.WbListData.Wb.getDefaultInstance());
      }
      public protobuf.data.wbList.WbListData.Wb.Builder addWbBuilder(
          int index) {
        return getWbFieldBuilder().addBuilder(
            index, protobuf.data.wbList.WbListData.Wb.getDefaultInstance());
      }
      public java.util.List<protobuf.data.wbList.WbListData.Wb.Builder> 
           getWbBuilderList() {
        return getWbFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.data.wbList.WbListData.Wb, protobuf.data.wbList.WbListData.Wb.Builder, protobuf.data.wbList.WbListData.WbOrBuilder> 
          getWbFieldBuilder() {
        if (wbBuilder_ == null) {
          wbBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.data.wbList.WbListData.Wb, protobuf.data.wbList.WbListData.Wb.Builder, protobuf.data.wbList.WbListData.WbOrBuilder>(
                  wb_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          wb_ = null;
        }
        return wbBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.WbList)
    }
    
    static {
      defaultInstance = new WbList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.WbList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025Protobuf/wpList.proto\022(com.oxseed.saas" +
      ".archive.ocr.servlet.data\"\036\n\002Wb\022\n\n\002id\030\001 " +
      "\002(\t\022\014\n\004type\030\002 \002(\t\"B\n\006WbList\0228\n\002wb\030\001 \003(\0132" +
      ",.com.oxseed.saas.archive.ocr.servlet.da" +
      "ta.WbB\"\n\024wbList.data.protobufB\nWbListDat" +
      "a"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_Wb_descriptor,
              new java.lang.String[] { "Id", "Type", },
              protobuf.data.wbList.WbListData.Wb.class,
              protobuf.data.wbList.WbListData.Wb.Builder.class);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_WbList_descriptor,
              new java.lang.String[] { "Wb", },
              protobuf.data.wbList.WbListData.WbList.class,
              protobuf.data.wbList.WbListData.WbList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
