// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf/indexList.proto

package protobuf.data.indexList;

public final class IndexListData {
  private IndexListData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CurrencyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string currency = 1;
    boolean hasCurrency();
    String getCurrency();
  }
  public static final class Currency extends
      com.google.protobuf.GeneratedMessage
      implements CurrencyOrBuilder {
    // Use Currency.newBuilder() to construct.
    private Currency(Builder builder) {
      super(builder);
    }
    private Currency(boolean noInit) {}
    
    private static final Currency defaultInstance;
    public static Currency getDefaultInstance() {
      return defaultInstance;
    }
    
    public Currency getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string currency = 1;
    public static final int CURRENCY_FIELD_NUMBER = 1;
    private java.lang.Object currency_;
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          currency_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      currency_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCurrency()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCurrencyBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCurrencyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.indexList.IndexListData.Currency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Currency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.data.indexList.IndexListData.Currency prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.data.indexList.IndexListData.CurrencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_fieldAccessorTable;
      }
      
      // Construct using indexList.data.protobuf.IndexListData.Currency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        currency_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.data.indexList.IndexListData.Currency.getDescriptor();
      }
      
      public protobuf.data.indexList.IndexListData.Currency getDefaultInstanceForType() {
        return protobuf.data.indexList.IndexListData.Currency.getDefaultInstance();
      }
      
      public protobuf.data.indexList.IndexListData.Currency build() {
        protobuf.data.indexList.IndexListData.Currency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.data.indexList.IndexListData.Currency buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.data.indexList.IndexListData.Currency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.data.indexList.IndexListData.Currency buildPartial() {
        protobuf.data.indexList.IndexListData.Currency result = new protobuf.data.indexList.IndexListData.Currency(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currency_ = currency_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.data.indexList.IndexListData.Currency) {
          return mergeFrom((protobuf.data.indexList.IndexListData.Currency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.data.indexList.IndexListData.Currency other) {
        if (other == protobuf.data.indexList.IndexListData.Currency.getDefaultInstance()) return this;
        if (other.hasCurrency()) {
          setCurrency(other.getCurrency());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCurrency()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              currency_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string currency = 1;
      private java.lang.Object currency_ = "";
      public boolean hasCurrency() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCurrency(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        currency_ = value;
        onChanged();
        return this;
      }
      public Builder clearCurrency() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      void setCurrency(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        currency_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.Currency)
    }
    
    static {
      defaultInstance = new Currency(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.Currency)
  }
  
  public interface IndexOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // optional string type = 2;
    boolean hasType();
    String getType();
    
    // optional string suffix = 3;
    boolean hasSuffix();
    String getSuffix();
    
    // optional string prefix = 4;
    boolean hasPrefix();
    String getPrefix();
    
    // optional string sorting = 5;
    boolean hasSorting();
    String getSorting();
    
    // optional string relatedTo = 6;
    boolean hasRelatedTo();
    String getRelatedTo();
    
    // optional string fulltextCreatorId = 7;
    boolean hasFulltextCreatorId();
    String getFulltextCreatorId();
    
    // optional string minLength = 8;
    boolean hasMinLength();
    String getMinLength();
    
    // optional string maxLength = 9;
    boolean hasMaxLength();
    String getMaxLength();
    
    // optional string decimalPrecision = 10;
    boolean hasDecimalPrecision();
    String getDecimalPrecision();
    
    // optional string multiple = 11;
    boolean hasMultiple();
    String getMultiple();
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Currency usedCurrencies = 12;
    java.util.List<protobuf.data.indexList.IndexListData.Currency> 
        getUsedCurrenciesList();
    protobuf.data.indexList.IndexListData.Currency getUsedCurrencies(int index);
    int getUsedCurrenciesCount();
    java.util.List<? extends protobuf.data.indexList.IndexListData.CurrencyOrBuilder> 
        getUsedCurrenciesOrBuilderList();
    protobuf.data.indexList.IndexListData.CurrencyOrBuilder getUsedCurrenciesOrBuilder(
        int index);
    
    // optional string shortcutKey = 15;
    boolean hasShortcutKey();
    String getShortcutKey();
  }
  public static final class Index extends
      com.google.protobuf.GeneratedMessage
      implements IndexOrBuilder {
    // Use Index.newBuilder() to construct.
    private Index(Builder builder) {
      super(builder);
    }
    private Index(boolean noInit) {}
    
    private static final Index defaultInstance;
    public static Index getDefaultInstance() {
      return defaultInstance;
    }
    
    public Index getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string suffix = 3;
    public static final int SUFFIX_FIELD_NUMBER = 3;
    private java.lang.Object suffix_;
    public boolean hasSuffix() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getSuffix() {
      java.lang.Object ref = suffix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          suffix_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSuffixBytes() {
      java.lang.Object ref = suffix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        suffix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string prefix = 4;
    public static final int PREFIX_FIELD_NUMBER = 4;
    private java.lang.Object prefix_;
    public boolean hasPrefix() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPrefix() {
      java.lang.Object ref = prefix_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          prefix_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPrefixBytes() {
      java.lang.Object ref = prefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        prefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string sorting = 5;
    public static final int SORTING_FIELD_NUMBER = 5;
    private java.lang.Object sorting_;
    public boolean hasSorting() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getSorting() {
      java.lang.Object ref = sorting_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          sorting_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSortingBytes() {
      java.lang.Object ref = sorting_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        sorting_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string relatedTo = 6;
    public static final int RELATEDTO_FIELD_NUMBER = 6;
    private java.lang.Object relatedTo_;
    public boolean hasRelatedTo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getRelatedTo() {
      java.lang.Object ref = relatedTo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          relatedTo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRelatedToBytes() {
      java.lang.Object ref = relatedTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        relatedTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string fulltextCreatorId = 7;
    public static final int FULLTEXTCREATORID_FIELD_NUMBER = 7;
    private java.lang.Object fulltextCreatorId_;
    public boolean hasFulltextCreatorId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getFulltextCreatorId() {
      java.lang.Object ref = fulltextCreatorId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fulltextCreatorId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFulltextCreatorIdBytes() {
      java.lang.Object ref = fulltextCreatorId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fulltextCreatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string minLength = 8;
    public static final int MINLENGTH_FIELD_NUMBER = 8;
    private java.lang.Object minLength_;
    public boolean hasMinLength() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getMinLength() {
      java.lang.Object ref = minLength_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          minLength_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMinLengthBytes() {
      java.lang.Object ref = minLength_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        minLength_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string maxLength = 9;
    public static final int MAXLENGTH_FIELD_NUMBER = 9;
    private java.lang.Object maxLength_;
    public boolean hasMaxLength() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getMaxLength() {
      java.lang.Object ref = maxLength_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          maxLength_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMaxLengthBytes() {
      java.lang.Object ref = maxLength_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        maxLength_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string decimalPrecision = 10;
    public static final int DECIMALPRECISION_FIELD_NUMBER = 10;
    private java.lang.Object decimalPrecision_;
    public boolean hasDecimalPrecision() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getDecimalPrecision() {
      java.lang.Object ref = decimalPrecision_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          decimalPrecision_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDecimalPrecisionBytes() {
      java.lang.Object ref = decimalPrecision_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        decimalPrecision_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string multiple = 11;
    public static final int MULTIPLE_FIELD_NUMBER = 11;
    private java.lang.Object multiple_;
    public boolean hasMultiple() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getMultiple() {
      java.lang.Object ref = multiple_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          multiple_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMultipleBytes() {
      java.lang.Object ref = multiple_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        multiple_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Currency usedCurrencies = 12;
    public static final int USEDCURRENCIES_FIELD_NUMBER = 12;
    private java.util.List<protobuf.data.indexList.IndexListData.Currency> usedCurrencies_;
    public java.util.List<protobuf.data.indexList.IndexListData.Currency> getUsedCurrenciesList() {
      return usedCurrencies_;
    }
    public java.util.List<? extends protobuf.data.indexList.IndexListData.CurrencyOrBuilder> 
        getUsedCurrenciesOrBuilderList() {
      return usedCurrencies_;
    }
    public int getUsedCurrenciesCount() {
      return usedCurrencies_.size();
    }
    public protobuf.data.indexList.IndexListData.Currency getUsedCurrencies(int index) {
      return usedCurrencies_.get(index);
    }
    public protobuf.data.indexList.IndexListData.CurrencyOrBuilder getUsedCurrenciesOrBuilder(
        int index) {
      return usedCurrencies_.get(index);
    }
    
    // optional string shortcutKey = 15;
    public static final int SHORTCUTKEY_FIELD_NUMBER = 15;
    private java.lang.Object shortcutKey_;
    public boolean hasShortcutKey() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getShortcutKey() {
      java.lang.Object ref = shortcutKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          shortcutKey_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getShortcutKeyBytes() {
      java.lang.Object ref = shortcutKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        shortcutKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      type_ = "";
      suffix_ = "";
      prefix_ = "";
      sorting_ = "";
      relatedTo_ = "";
      fulltextCreatorId_ = "";
      minLength_ = "";
      maxLength_ = "";
      decimalPrecision_ = "";
      multiple_ = "";
      usedCurrencies_ = java.util.Collections.emptyList();
      shortcutKey_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUsedCurrenciesCount(); i++) {
        if (!getUsedCurrencies(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSuffixBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPrefixBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getSortingBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getRelatedToBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getFulltextCreatorIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getMinLengthBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMaxLengthBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getDecimalPrecisionBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getMultipleBytes());
      }
      for (int i = 0; i < usedCurrencies_.size(); i++) {
        output.writeMessage(12, usedCurrencies_.get(i));
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(15, getShortcutKeyBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSuffixBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPrefixBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSortingBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getRelatedToBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getFulltextCreatorIdBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getMinLengthBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMaxLengthBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getDecimalPrecisionBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getMultipleBytes());
      }
      for (int i = 0; i < usedCurrencies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, usedCurrencies_.get(i));
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(15, getShortcutKeyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.data.indexList.IndexListData.Index parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.indexList.IndexListData.Index parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.Index parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.data.indexList.IndexListData.Index prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.data.indexList.IndexListData.IndexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_fieldAccessorTable;
      }
      
      // Construct using indexList.data.protobuf.IndexListData.Index.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUsedCurrenciesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        suffix_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        prefix_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        sorting_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        relatedTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        fulltextCreatorId_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        minLength_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        maxLength_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        decimalPrecision_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        multiple_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        if (usedCurrenciesBuilder_ == null) {
          usedCurrencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000800);
        } else {
          usedCurrenciesBuilder_.clear();
        }
        shortcutKey_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.data.indexList.IndexListData.Index.getDescriptor();
      }
      
      public protobuf.data.indexList.IndexListData.Index getDefaultInstanceForType() {
        return protobuf.data.indexList.IndexListData.Index.getDefaultInstance();
      }
      
      public protobuf.data.indexList.IndexListData.Index build() {
        protobuf.data.indexList.IndexListData.Index result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.data.indexList.IndexListData.Index buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.data.indexList.IndexListData.Index result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.data.indexList.IndexListData.Index buildPartial() {
        protobuf.data.indexList.IndexListData.Index result = new protobuf.data.indexList.IndexListData.Index(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.suffix_ = suffix_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prefix_ = prefix_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sorting_ = sorting_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.relatedTo_ = relatedTo_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.fulltextCreatorId_ = fulltextCreatorId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.minLength_ = minLength_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.maxLength_ = maxLength_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.decimalPrecision_ = decimalPrecision_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.multiple_ = multiple_;
        if (usedCurrenciesBuilder_ == null) {
          if (((bitField0_ & 0x00000800) == 0x00000800)) {
            usedCurrencies_ = java.util.Collections.unmodifiableList(usedCurrencies_);
            bitField0_ = (bitField0_ & ~0x00000800);
          }
          result.usedCurrencies_ = usedCurrencies_;
        } else {
          result.usedCurrencies_ = usedCurrenciesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.shortcutKey_ = shortcutKey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.data.indexList.IndexListData.Index) {
          return mergeFrom((protobuf.data.indexList.IndexListData.Index)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.data.indexList.IndexListData.Index other) {
        if (other == protobuf.data.indexList.IndexListData.Index.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSuffix()) {
          setSuffix(other.getSuffix());
        }
        if (other.hasPrefix()) {
          setPrefix(other.getPrefix());
        }
        if (other.hasSorting()) {
          setSorting(other.getSorting());
        }
        if (other.hasRelatedTo()) {
          setRelatedTo(other.getRelatedTo());
        }
        if (other.hasFulltextCreatorId()) {
          setFulltextCreatorId(other.getFulltextCreatorId());
        }
        if (other.hasMinLength()) {
          setMinLength(other.getMinLength());
        }
        if (other.hasMaxLength()) {
          setMaxLength(other.getMaxLength());
        }
        if (other.hasDecimalPrecision()) {
          setDecimalPrecision(other.getDecimalPrecision());
        }
        if (other.hasMultiple()) {
          setMultiple(other.getMultiple());
        }
        if (usedCurrenciesBuilder_ == null) {
          if (!other.usedCurrencies_.isEmpty()) {
            if (usedCurrencies_.isEmpty()) {
              usedCurrencies_ = other.usedCurrencies_;
              bitField0_ = (bitField0_ & ~0x00000800);
            } else {
              ensureUsedCurrenciesIsMutable();
              usedCurrencies_.addAll(other.usedCurrencies_);
            }
            onChanged();
          }
        } else {
          if (!other.usedCurrencies_.isEmpty()) {
            if (usedCurrenciesBuilder_.isEmpty()) {
              usedCurrenciesBuilder_.dispose();
              usedCurrenciesBuilder_ = null;
              usedCurrencies_ = other.usedCurrencies_;
              bitField0_ = (bitField0_ & ~0x00000800);
              usedCurrenciesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getUsedCurrenciesFieldBuilder() : null;
            } else {
              usedCurrenciesBuilder_.addAllMessages(other.usedCurrencies_);
            }
          }
        }
        if (other.hasShortcutKey()) {
          setShortcutKey(other.getShortcutKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getUsedCurrenciesCount(); i++) {
          if (!getUsedCurrencies(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              type_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              suffix_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              prefix_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              sorting_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              relatedTo_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              fulltextCreatorId_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              minLength_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              maxLength_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              decimalPrecision_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              multiple_ = input.readBytes();
              break;
            }
            case 98: {
              protobuf.data.indexList.IndexListData.Currency.Builder subBuilder = protobuf.data.indexList.IndexListData.Currency.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addUsedCurrencies(subBuilder.buildPartial());
              break;
            }
            case 122: {
              bitField0_ |= 0x00001000;
              shortcutKey_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string type = 2;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
      }
      
      // optional string suffix = 3;
      private java.lang.Object suffix_ = "";
      public boolean hasSuffix() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getSuffix() {
        java.lang.Object ref = suffix_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          suffix_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSuffix(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        suffix_ = value;
        onChanged();
        return this;
      }
      public Builder clearSuffix() {
        bitField0_ = (bitField0_ & ~0x00000004);
        suffix_ = getDefaultInstance().getSuffix();
        onChanged();
        return this;
      }
      void setSuffix(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        suffix_ = value;
        onChanged();
      }
      
      // optional string prefix = 4;
      private java.lang.Object prefix_ = "";
      public boolean hasPrefix() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPrefix() {
        java.lang.Object ref = prefix_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          prefix_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPrefix(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        prefix_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrefix() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prefix_ = getDefaultInstance().getPrefix();
        onChanged();
        return this;
      }
      void setPrefix(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        prefix_ = value;
        onChanged();
      }
      
      // optional string sorting = 5;
      private java.lang.Object sorting_ = "";
      public boolean hasSorting() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getSorting() {
        java.lang.Object ref = sorting_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          sorting_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSorting(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sorting_ = value;
        onChanged();
        return this;
      }
      public Builder clearSorting() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sorting_ = getDefaultInstance().getSorting();
        onChanged();
        return this;
      }
      void setSorting(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        sorting_ = value;
        onChanged();
      }
      
      // optional string relatedTo = 6;
      private java.lang.Object relatedTo_ = "";
      public boolean hasRelatedTo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getRelatedTo() {
        java.lang.Object ref = relatedTo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          relatedTo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRelatedTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        relatedTo_ = value;
        onChanged();
        return this;
      }
      public Builder clearRelatedTo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        relatedTo_ = getDefaultInstance().getRelatedTo();
        onChanged();
        return this;
      }
      void setRelatedTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        relatedTo_ = value;
        onChanged();
      }
      
      // optional string fulltextCreatorId = 7;
      private java.lang.Object fulltextCreatorId_ = "";
      public boolean hasFulltextCreatorId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getFulltextCreatorId() {
        java.lang.Object ref = fulltextCreatorId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fulltextCreatorId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFulltextCreatorId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        fulltextCreatorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearFulltextCreatorId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        fulltextCreatorId_ = getDefaultInstance().getFulltextCreatorId();
        onChanged();
        return this;
      }
      void setFulltextCreatorId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        fulltextCreatorId_ = value;
        onChanged();
      }
      
      // optional string minLength = 8;
      private java.lang.Object minLength_ = "";
      public boolean hasMinLength() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getMinLength() {
        java.lang.Object ref = minLength_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          minLength_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMinLength(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        minLength_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinLength() {
        bitField0_ = (bitField0_ & ~0x00000080);
        minLength_ = getDefaultInstance().getMinLength();
        onChanged();
        return this;
      }
      void setMinLength(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        minLength_ = value;
        onChanged();
      }
      
      // optional string maxLength = 9;
      private java.lang.Object maxLength_ = "";
      public boolean hasMaxLength() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getMaxLength() {
        java.lang.Object ref = maxLength_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          maxLength_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMaxLength(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        maxLength_ = value;
        onChanged();
        return this;
      }
      public Builder clearMaxLength() {
        bitField0_ = (bitField0_ & ~0x00000100);
        maxLength_ = getDefaultInstance().getMaxLength();
        onChanged();
        return this;
      }
      void setMaxLength(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        maxLength_ = value;
        onChanged();
      }
      
      // optional string decimalPrecision = 10;
      private java.lang.Object decimalPrecision_ = "";
      public boolean hasDecimalPrecision() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getDecimalPrecision() {
        java.lang.Object ref = decimalPrecision_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          decimalPrecision_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDecimalPrecision(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        decimalPrecision_ = value;
        onChanged();
        return this;
      }
      public Builder clearDecimalPrecision() {
        bitField0_ = (bitField0_ & ~0x00000200);
        decimalPrecision_ = getDefaultInstance().getDecimalPrecision();
        onChanged();
        return this;
      }
      void setDecimalPrecision(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        decimalPrecision_ = value;
        onChanged();
      }
      
      // optional string multiple = 11;
      private java.lang.Object multiple_ = "";
      public boolean hasMultiple() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getMultiple() {
        java.lang.Object ref = multiple_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          multiple_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMultiple(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        multiple_ = value;
        onChanged();
        return this;
      }
      public Builder clearMultiple() {
        bitField0_ = (bitField0_ & ~0x00000400);
        multiple_ = getDefaultInstance().getMultiple();
        onChanged();
        return this;
      }
      void setMultiple(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        multiple_ = value;
        onChanged();
      }
      
      // repeated .com.oxseed.saas.archive.ocr.servlet.data.Currency usedCurrencies = 12;
      private java.util.List<protobuf.data.indexList.IndexListData.Currency> usedCurrencies_ =
        java.util.Collections.emptyList();
      private void ensureUsedCurrenciesIsMutable() {
        if (!((bitField0_ & 0x00000800) == 0x00000800)) {
          usedCurrencies_ = new java.util.ArrayList<protobuf.data.indexList.IndexListData.Currency>(usedCurrencies_);
          bitField0_ |= 0x00000800;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.data.indexList.IndexListData.Currency, protobuf.data.indexList.IndexListData.Currency.Builder, protobuf.data.indexList.IndexListData.CurrencyOrBuilder> usedCurrenciesBuilder_;
      
      public java.util.List<protobuf.data.indexList.IndexListData.Currency> getUsedCurrenciesList() {
        if (usedCurrenciesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(usedCurrencies_);
        } else {
          return usedCurrenciesBuilder_.getMessageList();
        }
      }
      public int getUsedCurrenciesCount() {
        if (usedCurrenciesBuilder_ == null) {
          return usedCurrencies_.size();
        } else {
          return usedCurrenciesBuilder_.getCount();
        }
      }
      public protobuf.data.indexList.IndexListData.Currency getUsedCurrencies(int index) {
        if (usedCurrenciesBuilder_ == null) {
          return usedCurrencies_.get(index);
        } else {
          return usedCurrenciesBuilder_.getMessage(index);
        }
      }
      public Builder setUsedCurrencies(
          int index, protobuf.data.indexList.IndexListData.Currency value) {
        if (usedCurrenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.set(index, value);
          onChanged();
        } else {
          usedCurrenciesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setUsedCurrencies(
          int index, protobuf.data.indexList.IndexListData.Currency.Builder builderForValue) {
        if (usedCurrenciesBuilder_ == null) {
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.set(index, builderForValue.build());
          onChanged();
        } else {
          usedCurrenciesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addUsedCurrencies(protobuf.data.indexList.IndexListData.Currency value) {
        if (usedCurrenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.add(value);
          onChanged();
        } else {
          usedCurrenciesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addUsedCurrencies(
          int index, protobuf.data.indexList.IndexListData.Currency value) {
        if (usedCurrenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.add(index, value);
          onChanged();
        } else {
          usedCurrenciesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addUsedCurrencies(
          protobuf.data.indexList.IndexListData.Currency.Builder builderForValue) {
        if (usedCurrenciesBuilder_ == null) {
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.add(builderForValue.build());
          onChanged();
        } else {
          usedCurrenciesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addUsedCurrencies(
          int index, protobuf.data.indexList.IndexListData.Currency.Builder builderForValue) {
        if (usedCurrenciesBuilder_ == null) {
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.add(index, builderForValue.build());
          onChanged();
        } else {
          usedCurrenciesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllUsedCurrencies(
          java.lang.Iterable<? extends protobuf.data.indexList.IndexListData.Currency> values) {
        if (usedCurrenciesBuilder_ == null) {
          ensureUsedCurrenciesIsMutable();
          super.addAll(values, usedCurrencies_);
          onChanged();
        } else {
          usedCurrenciesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearUsedCurrencies() {
        if (usedCurrenciesBuilder_ == null) {
          usedCurrencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000800);
          onChanged();
        } else {
          usedCurrenciesBuilder_.clear();
        }
        return this;
      }
      public Builder removeUsedCurrencies(int index) {
        if (usedCurrenciesBuilder_ == null) {
          ensureUsedCurrenciesIsMutable();
          usedCurrencies_.remove(index);
          onChanged();
        } else {
          usedCurrenciesBuilder_.remove(index);
        }
        return this;
      }
      public protobuf.data.indexList.IndexListData.Currency.Builder getUsedCurrenciesBuilder(
          int index) {
        return getUsedCurrenciesFieldBuilder().getBuilder(index);
      }
      public protobuf.data.indexList.IndexListData.CurrencyOrBuilder getUsedCurrenciesOrBuilder(
          int index) {
        if (usedCurrenciesBuilder_ == null) {
          return usedCurrencies_.get(index);  } else {
          return usedCurrenciesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf.data.indexList.IndexListData.CurrencyOrBuilder> 
           getUsedCurrenciesOrBuilderList() {
        if (usedCurrenciesBuilder_ != null) {
          return usedCurrenciesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(usedCurrencies_);
        }
      }
      public protobuf.data.indexList.IndexListData.Currency.Builder addUsedCurrenciesBuilder() {
        return getUsedCurrenciesFieldBuilder().addBuilder(
            protobuf.data.indexList.IndexListData.Currency.getDefaultInstance());
      }
      public protobuf.data.indexList.IndexListData.Currency.Builder addUsedCurrenciesBuilder(
          int index) {
        return getUsedCurrenciesFieldBuilder().addBuilder(
            index, protobuf.data.indexList.IndexListData.Currency.getDefaultInstance());
      }
      public java.util.List<protobuf.data.indexList.IndexListData.Currency.Builder> 
           getUsedCurrenciesBuilderList() {
        return getUsedCurrenciesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.data.indexList.IndexListData.Currency, protobuf.data.indexList.IndexListData.Currency.Builder, protobuf.data.indexList.IndexListData.CurrencyOrBuilder> 
          getUsedCurrenciesFieldBuilder() {
        if (usedCurrenciesBuilder_ == null) {
          usedCurrenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.data.indexList.IndexListData.Currency, protobuf.data.indexList.IndexListData.Currency.Builder, protobuf.data.indexList.IndexListData.CurrencyOrBuilder>(
                  usedCurrencies_,
                  ((bitField0_ & 0x00000800) == 0x00000800),
                  getParentForChildren(),
                  isClean());
          usedCurrencies_ = null;
        }
        return usedCurrenciesBuilder_;
      }
      
      // optional string shortcutKey = 15;
      private java.lang.Object shortcutKey_ = "";
      public boolean hasShortcutKey() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getShortcutKey() {
        java.lang.Object ref = shortcutKey_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          shortcutKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setShortcutKey(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        shortcutKey_ = value;
        onChanged();
        return this;
      }
      public Builder clearShortcutKey() {
        bitField0_ = (bitField0_ & ~0x00001000);
        shortcutKey_ = getDefaultInstance().getShortcutKey();
        onChanged();
        return this;
      }
      void setShortcutKey(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        shortcutKey_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.Index)
    }
    
    static {
      defaultInstance = new Index(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.Index)
  }
  
  public interface IndexListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Index index = 1;
    java.util.List<protobuf.data.indexList.IndexListData.Index> 
        getIndexList();
    protobuf.data.indexList.IndexListData.Index getIndex(int index);
    int getIndexCount();
    java.util.List<? extends protobuf.data.indexList.IndexListData.IndexOrBuilder> 
        getIndexOrBuilderList();
    protobuf.data.indexList.IndexListData.IndexOrBuilder getIndexOrBuilder(
        int index);
  }
  public static final class IndexList extends
      com.google.protobuf.GeneratedMessage
      implements IndexListOrBuilder {
    // Use IndexList.newBuilder() to construct.
    private IndexList(Builder builder) {
      super(builder);
    }
    private IndexList(boolean noInit) {}
    
    private static final IndexList defaultInstance;
    public static IndexList getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_fieldAccessorTable;
    }
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Index index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private java.util.List<protobuf.data.indexList.IndexListData.Index> index_;
    public java.util.List<protobuf.data.indexList.IndexListData.Index> getIndexList() {
      return index_;
    }
    public java.util.List<? extends protobuf.data.indexList.IndexListData.IndexOrBuilder> 
        getIndexOrBuilderList() {
      return index_;
    }
    public int getIndexCount() {
      return index_.size();
    }
    public protobuf.data.indexList.IndexListData.Index getIndex(int index) {
      return index_.get(index);
    }
    public protobuf.data.indexList.IndexListData.IndexOrBuilder getIndexOrBuilder(
        int index) {
      return index_.get(index);
    }
    
    private void initFields() {
      index_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getIndexCount(); i++) {
        if (!getIndex(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < index_.size(); i++) {
        output.writeMessage(1, index_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < index_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, index_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.indexList.IndexListData.IndexList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.data.indexList.IndexListData.IndexList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.data.indexList.IndexListData.IndexListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.data.indexList.IndexListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_fieldAccessorTable;
      }
      
      // Construct using indexList.data.protobuf.IndexListData.IndexList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIndexFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (indexBuilder_ == null) {
          index_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          indexBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.data.indexList.IndexListData.IndexList.getDescriptor();
      }
      
      public protobuf.data.indexList.IndexListData.IndexList getDefaultInstanceForType() {
        return protobuf.data.indexList.IndexListData.IndexList.getDefaultInstance();
      }
      
      public protobuf.data.indexList.IndexListData.IndexList build() {
        protobuf.data.indexList.IndexListData.IndexList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.data.indexList.IndexListData.IndexList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.data.indexList.IndexListData.IndexList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.data.indexList.IndexListData.IndexList buildPartial() {
        protobuf.data.indexList.IndexListData.IndexList result = new protobuf.data.indexList.IndexListData.IndexList(this);
        int from_bitField0_ = bitField0_;
        if (indexBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            index_ = java.util.Collections.unmodifiableList(index_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.index_ = index_;
        } else {
          result.index_ = indexBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.data.indexList.IndexListData.IndexList) {
          return mergeFrom((protobuf.data.indexList.IndexListData.IndexList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.data.indexList.IndexListData.IndexList other) {
        if (other == protobuf.data.indexList.IndexListData.IndexList.getDefaultInstance()) return this;
        if (indexBuilder_ == null) {
          if (!other.index_.isEmpty()) {
            if (index_.isEmpty()) {
              index_ = other.index_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIndexIsMutable();
              index_.addAll(other.index_);
            }
            onChanged();
          }
        } else {
          if (!other.index_.isEmpty()) {
            if (indexBuilder_.isEmpty()) {
              indexBuilder_.dispose();
              indexBuilder_ = null;
              index_ = other.index_;
              bitField0_ = (bitField0_ & ~0x00000001);
              indexBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIndexFieldBuilder() : null;
            } else {
              indexBuilder_.addAllMessages(other.index_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getIndexCount(); i++) {
          if (!getIndex(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              protobuf.data.indexList.IndexListData.Index.Builder subBuilder = protobuf.data.indexList.IndexListData.Index.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIndex(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.oxseed.saas.archive.ocr.servlet.data.Index index = 1;
      private java.util.List<protobuf.data.indexList.IndexListData.Index> index_ =
        java.util.Collections.emptyList();
      private void ensureIndexIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          index_ = new java.util.ArrayList<protobuf.data.indexList.IndexListData.Index>(index_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.data.indexList.IndexListData.Index, protobuf.data.indexList.IndexListData.Index.Builder, protobuf.data.indexList.IndexListData.IndexOrBuilder> indexBuilder_;
      
      public java.util.List<protobuf.data.indexList.IndexListData.Index> getIndexList() {
        if (indexBuilder_ == null) {
          return java.util.Collections.unmodifiableList(index_);
        } else {
          return indexBuilder_.getMessageList();
        }
      }
      public int getIndexCount() {
        if (indexBuilder_ == null) {
          return index_.size();
        } else {
          return indexBuilder_.getCount();
        }
      }
      public protobuf.data.indexList.IndexListData.Index getIndex(int index) {
        if (indexBuilder_ == null) {
          return index_.get(index);
        } else {
          return indexBuilder_.getMessage(index);
        }
      }
      public Builder setIndex(
          int index, protobuf.data.indexList.IndexListData.Index value) {
        if (indexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexIsMutable();
          index_.set(index, value);
          onChanged();
        } else {
          indexBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setIndex(
          int index, protobuf.data.indexList.IndexListData.Index.Builder builderForValue) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.set(index, builderForValue.build());
          onChanged();
        } else {
          indexBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addIndex(protobuf.data.indexList.IndexListData.Index value) {
        if (indexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexIsMutable();
          index_.add(value);
          onChanged();
        } else {
          indexBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addIndex(
          int index, protobuf.data.indexList.IndexListData.Index value) {
        if (indexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexIsMutable();
          index_.add(index, value);
          onChanged();
        } else {
          indexBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addIndex(
          protobuf.data.indexList.IndexListData.Index.Builder builderForValue) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.add(builderForValue.build());
          onChanged();
        } else {
          indexBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addIndex(
          int index, protobuf.data.indexList.IndexListData.Index.Builder builderForValue) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.add(index, builderForValue.build());
          onChanged();
        } else {
          indexBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllIndex(
          java.lang.Iterable<? extends protobuf.data.indexList.IndexListData.Index> values) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          super.addAll(values, index_);
          onChanged();
        } else {
          indexBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearIndex() {
        if (indexBuilder_ == null) {
          index_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          indexBuilder_.clear();
        }
        return this;
      }
      public Builder removeIndex(int index) {
        if (indexBuilder_ == null) {
          ensureIndexIsMutable();
          index_.remove(index);
          onChanged();
        } else {
          indexBuilder_.remove(index);
        }
        return this;
      }
      public protobuf.data.indexList.IndexListData.Index.Builder getIndexBuilder(
          int index) {
        return getIndexFieldBuilder().getBuilder(index);
      }
      public protobuf.data.indexList.IndexListData.IndexOrBuilder getIndexOrBuilder(
          int index) {
        if (indexBuilder_ == null) {
          return index_.get(index);  } else {
          return indexBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protobuf.data.indexList.IndexListData.IndexOrBuilder> 
           getIndexOrBuilderList() {
        if (indexBuilder_ != null) {
          return indexBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(index_);
        }
      }
      public protobuf.data.indexList.IndexListData.Index.Builder addIndexBuilder() {
        return getIndexFieldBuilder().addBuilder(
            protobuf.data.indexList.IndexListData.Index.getDefaultInstance());
      }
      public protobuf.data.indexList.IndexListData.Index.Builder addIndexBuilder(
          int index) {
        return getIndexFieldBuilder().addBuilder(
            index, protobuf.data.indexList.IndexListData.Index.getDefaultInstance());
      }
      public java.util.List<protobuf.data.indexList.IndexListData.Index.Builder> 
           getIndexBuilderList() {
        return getIndexFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.data.indexList.IndexListData.Index, protobuf.data.indexList.IndexListData.Index.Builder, protobuf.data.indexList.IndexListData.IndexOrBuilder> 
          getIndexFieldBuilder() {
        if (indexBuilder_ == null) {
          indexBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.data.indexList.IndexListData.Index, protobuf.data.indexList.IndexListData.Index.Builder, protobuf.data.indexList.IndexListData.IndexOrBuilder>(
                  index_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          index_ = null;
        }
        return indexBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.IndexList)
    }
    
    static {
      defaultInstance = new IndexList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.IndexList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030Protobuf/indexList.proto\022(com.oxseed.s" +
      "aas.archive.ocr.servlet.data\"\034\n\010Currency" +
      "\022\020\n\010currency\030\001 \002(\t\"\263\002\n\005Index\022\n\n\002id\030\001 \002(\t" +
      "\022\014\n\004type\030\002 \001(\t\022\016\n\006suffix\030\003 \001(\t\022\016\n\006prefix" +
      "\030\004 \001(\t\022\017\n\007sorting\030\005 \001(\t\022\021\n\trelatedTo\030\006 \001" +
      "(\t\022\031\n\021fulltextCreatorId\030\007 \001(\t\022\021\n\tminLeng" +
      "th\030\010 \001(\t\022\021\n\tmaxLength\030\t \001(\t\022\030\n\020decimalPr" +
      "ecision\030\n \001(\t\022\020\n\010multiple\030\013 \001(\t\022J\n\016usedC" +
      "urrencies\030\014 \003(\01322.com.oxseed.saas.archiv" +
      "e.ocr.servlet.data.Currency\022\023\n\013shortcutK",
      "ey\030\017 \001(\t\"K\n\tIndexList\022>\n\005index\030\001 \003(\0132/.c" +
      "om.oxseed.saas.archive.ocr.servlet.data." +
      "IndexB(\n\027indexList.data.protobufB\rIndexL" +
      "istData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_Currency_descriptor,
              new java.lang.String[] { "Currency", },
              protobuf.data.indexList.IndexListData.Currency.class,
              protobuf.data.indexList.IndexListData.Currency.Builder.class);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_Index_descriptor,
              new java.lang.String[] { "Id", "Type", "Suffix", "Prefix", "Sorting", "RelatedTo", "FulltextCreatorId", "MinLength", "MaxLength", "DecimalPrecision", "Multiple", "UsedCurrencies", "ShortcutKey", },
              protobuf.data.indexList.IndexListData.Index.class,
              protobuf.data.indexList.IndexListData.Index.Builder.class);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_IndexList_descriptor,
              new java.lang.String[] { "Index", },
              protobuf.data.indexList.IndexListData.IndexList.class,
              protobuf.data.indexList.IndexListData.IndexList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
