// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf/processTypeIdList.proto

package protobuf.data.processTypeIdList;

public final class ProcessTypeIdListData {
  private ProcessTypeIdListData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProcessTypeIdListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string processTypeId = 1;
    java.util.List<String> getProcessTypeIdList();
    int getProcessTypeIdCount();
    String getProcessTypeId(int index);
  }
  public static final class ProcessTypeIdList extends
      com.google.protobuf.GeneratedMessage
      implements ProcessTypeIdListOrBuilder {
    // Use ProcessTypeIdList.newBuilder() to construct.
    private ProcessTypeIdList(Builder builder) {
      super(builder);
    }
    private ProcessTypeIdList(boolean noInit) {}
    
    private static final ProcessTypeIdList defaultInstance;
    public static ProcessTypeIdList getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProcessTypeIdList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.data.processTypeIdList.ProcessTypeIdListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.data.processTypeIdList.ProcessTypeIdListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_fieldAccessorTable;
    }
    
    // repeated string processTypeId = 1;
    public static final int PROCESSTYPEID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList processTypeId_;
    public java.util.List<String>
        getProcessTypeIdList() {
      return processTypeId_;
    }
    public int getProcessTypeIdCount() {
      return processTypeId_.size();
    }
    public String getProcessTypeId(int index) {
      return processTypeId_.get(index);
    }
    
    private void initFields() {
      processTypeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < processTypeId_.size(); i++) {
        output.writeBytes(1, processTypeId_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < processTypeId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(processTypeId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getProcessTypeIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.data.processTypeIdList.ProcessTypeIdListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.data.processTypeIdList.ProcessTypeIdListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_fieldAccessorTable;
      }
      
      // Construct using processTypeIdList.data.protobuf.ProcesssTypeIdListData.ProcessTypeIdList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        processTypeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList.getDescriptor();
      }
      
      public protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList getDefaultInstanceForType() {
        return protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList.getDefaultInstance();
      }
      
      public protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList build() {
        protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList buildPartial() {
        protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList result = new protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          processTypeId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              processTypeId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.processTypeId_ = processTypeId_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList) {
          return mergeFrom((protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList other) {
        if (other == protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList.getDefaultInstance()) return this;
        if (!other.processTypeId_.isEmpty()) {
          if (processTypeId_.isEmpty()) {
            processTypeId_ = other.processTypeId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureProcessTypeIdIsMutable();
            processTypeId_.addAll(other.processTypeId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureProcessTypeIdIsMutable();
              processTypeId_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string processTypeId = 1;
      private com.google.protobuf.LazyStringList processTypeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureProcessTypeIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          processTypeId_ = new com.google.protobuf.LazyStringArrayList(processTypeId_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getProcessTypeIdList() {
        return java.util.Collections.unmodifiableList(processTypeId_);
      }
      public int getProcessTypeIdCount() {
        return processTypeId_.size();
      }
      public String getProcessTypeId(int index) {
        return processTypeId_.get(index);
      }
      public Builder setProcessTypeId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProcessTypeIdIsMutable();
        processTypeId_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addProcessTypeId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureProcessTypeIdIsMutable();
        processTypeId_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllProcessTypeId(
          java.lang.Iterable<String> values) {
        ensureProcessTypeIdIsMutable();
        super.addAll(values, processTypeId_);
        onChanged();
        return this;
      }
      public Builder clearProcessTypeId() {
        processTypeId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addProcessTypeId(com.google.protobuf.ByteString value) {
        ensureProcessTypeIdIsMutable();
        processTypeId_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.ProcessTypeIdList)
    }
    
    static {
      defaultInstance = new ProcessTypeIdList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.ProcessTypeIdList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n Protobuf/processTypeIdList.proto\022(com." +
      "oxseed.saas.archive.ocr.servlet.data\"*\n\021" +
      "ProcessTypeIdList\022\025\n\rprocessTypeId\030\001 \003(\t" +
      "B9\n\037processTypeIdList.data.protobufB\026Pro" +
      "cesssTypeIdListData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_ProcessTypeIdList_descriptor,
              new java.lang.String[] { "ProcessTypeId", },
              protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList.class,
              protobuf.data.processTypeIdList.ProcessTypeIdListData.ProcessTypeIdList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
