// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protobuf/commandlist.proto

package commandlist.data.protobuf;

public final class CommandListData {
  private CommandListData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
  }
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(Builder builder) {
      super(builder);
    }
    private Command(boolean noInit) {}
    
    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }
    
    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static commandlist.data.protobuf.CommandListData.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(commandlist.data.protobuf.CommandListData.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements commandlist.data.protobuf.CommandListData.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_fieldAccessorTable;
      }
      
      // Construct using commandlist.data.protobuf.CommandListData.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return commandlist.data.protobuf.CommandListData.Command.getDescriptor();
      }
      
      public commandlist.data.protobuf.CommandListData.Command getDefaultInstanceForType() {
        return commandlist.data.protobuf.CommandListData.Command.getDefaultInstance();
      }
      
      public commandlist.data.protobuf.CommandListData.Command build() {
        commandlist.data.protobuf.CommandListData.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private commandlist.data.protobuf.CommandListData.Command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        commandlist.data.protobuf.CommandListData.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public commandlist.data.protobuf.CommandListData.Command buildPartial() {
        commandlist.data.protobuf.CommandListData.Command result = new commandlist.data.protobuf.CommandListData.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof commandlist.data.protobuf.CommandListData.Command) {
          return mergeFrom((commandlist.data.protobuf.CommandListData.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(commandlist.data.protobuf.CommandListData.Command other) {
        if (other == commandlist.data.protobuf.CommandListData.Command.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.Command)
    }
    
    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.Command)
  }
  
  public interface CommandListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Command command = 1;
    java.util.List<commandlist.data.protobuf.CommandListData.Command> 
        getCommandList();
    commandlist.data.protobuf.CommandListData.Command getCommand(int index);
    int getCommandCount();
    java.util.List<? extends commandlist.data.protobuf.CommandListData.CommandOrBuilder> 
        getCommandOrBuilderList();
    commandlist.data.protobuf.CommandListData.CommandOrBuilder getCommandOrBuilder(
        int index);
  }
  public static final class CommandList extends
      com.google.protobuf.GeneratedMessage
      implements CommandListOrBuilder {
    // Use CommandList.newBuilder() to construct.
    private CommandList(Builder builder) {
      super(builder);
    }
    private CommandList(boolean noInit) {}
    
    private static final CommandList defaultInstance;
    public static CommandList getDefaultInstance() {
      return defaultInstance;
    }
    
    public CommandList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_fieldAccessorTable;
    }
    
    // repeated .com.oxseed.saas.archive.ocr.servlet.data.Command command = 1;
    public static final int COMMAND_FIELD_NUMBER = 1;
    private java.util.List<commandlist.data.protobuf.CommandListData.Command> command_;
    public java.util.List<commandlist.data.protobuf.CommandListData.Command> getCommandList() {
      return command_;
    }
    public java.util.List<? extends commandlist.data.protobuf.CommandListData.CommandOrBuilder> 
        getCommandOrBuilderList() {
      return command_;
    }
    public int getCommandCount() {
      return command_.size();
    }
    public commandlist.data.protobuf.CommandListData.Command getCommand(int index) {
      return command_.get(index);
    }
    public commandlist.data.protobuf.CommandListData.CommandOrBuilder getCommandOrBuilder(
        int index) {
      return command_.get(index);
    }
    
    private void initFields() {
      command_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getCommandCount(); i++) {
        if (!getCommand(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < command_.size(); i++) {
        output.writeMessage(1, command_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < command_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, command_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static commandlist.data.protobuf.CommandListData.CommandList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(commandlist.data.protobuf.CommandListData.CommandList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements commandlist.data.protobuf.CommandListData.CommandListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return commandlist.data.protobuf.CommandListData.internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_fieldAccessorTable;
      }
      
      // Construct using commandlist.data.protobuf.CommandListData.CommandList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCommandFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (commandBuilder_ == null) {
          command_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          commandBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return commandlist.data.protobuf.CommandListData.CommandList.getDescriptor();
      }
      
      public commandlist.data.protobuf.CommandListData.CommandList getDefaultInstanceForType() {
        return commandlist.data.protobuf.CommandListData.CommandList.getDefaultInstance();
      }
      
      public commandlist.data.protobuf.CommandListData.CommandList build() {
        commandlist.data.protobuf.CommandListData.CommandList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private commandlist.data.protobuf.CommandListData.CommandList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        commandlist.data.protobuf.CommandListData.CommandList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public commandlist.data.protobuf.CommandListData.CommandList buildPartial() {
        commandlist.data.protobuf.CommandListData.CommandList result = new commandlist.data.protobuf.CommandListData.CommandList(this);
        int from_bitField0_ = bitField0_;
        if (commandBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            command_ = java.util.Collections.unmodifiableList(command_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.command_ = command_;
        } else {
          result.command_ = commandBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof commandlist.data.protobuf.CommandListData.CommandList) {
          return mergeFrom((commandlist.data.protobuf.CommandListData.CommandList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(commandlist.data.protobuf.CommandListData.CommandList other) {
        if (other == commandlist.data.protobuf.CommandListData.CommandList.getDefaultInstance()) return this;
        if (commandBuilder_ == null) {
          if (!other.command_.isEmpty()) {
            if (command_.isEmpty()) {
              command_ = other.command_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCommandIsMutable();
              command_.addAll(other.command_);
            }
            onChanged();
          }
        } else {
          if (!other.command_.isEmpty()) {
            if (commandBuilder_.isEmpty()) {
              commandBuilder_.dispose();
              commandBuilder_ = null;
              command_ = other.command_;
              bitField0_ = (bitField0_ & ~0x00000001);
              commandBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCommandFieldBuilder() : null;
            } else {
              commandBuilder_.addAllMessages(other.command_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getCommandCount(); i++) {
          if (!getCommand(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              commandlist.data.protobuf.CommandListData.Command.Builder subBuilder = commandlist.data.protobuf.CommandListData.Command.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addCommand(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.oxseed.saas.archive.ocr.servlet.data.Command command = 1;
      private java.util.List<commandlist.data.protobuf.CommandListData.Command> command_ =
        java.util.Collections.emptyList();
      private void ensureCommandIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          command_ = new java.util.ArrayList<commandlist.data.protobuf.CommandListData.Command>(command_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          commandlist.data.protobuf.CommandListData.Command, commandlist.data.protobuf.CommandListData.Command.Builder, commandlist.data.protobuf.CommandListData.CommandOrBuilder> commandBuilder_;
      
      public java.util.List<commandlist.data.protobuf.CommandListData.Command> getCommandList() {
        if (commandBuilder_ == null) {
          return java.util.Collections.unmodifiableList(command_);
        } else {
          return commandBuilder_.getMessageList();
        }
      }
      public int getCommandCount() {
        if (commandBuilder_ == null) {
          return command_.size();
        } else {
          return commandBuilder_.getCount();
        }
      }
      public commandlist.data.protobuf.CommandListData.Command getCommand(int index) {
        if (commandBuilder_ == null) {
          return command_.get(index);
        } else {
          return commandBuilder_.getMessage(index);
        }
      }
      public Builder setCommand(
          int index, commandlist.data.protobuf.CommandListData.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandIsMutable();
          command_.set(index, value);
          onChanged();
        } else {
          commandBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setCommand(
          int index, commandlist.data.protobuf.CommandListData.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.set(index, builderForValue.build());
          onChanged();
        } else {
          commandBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addCommand(commandlist.data.protobuf.CommandListData.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandIsMutable();
          command_.add(value);
          onChanged();
        } else {
          commandBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addCommand(
          int index, commandlist.data.protobuf.CommandListData.Command value) {
        if (commandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCommandIsMutable();
          command_.add(index, value);
          onChanged();
        } else {
          commandBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addCommand(
          commandlist.data.protobuf.CommandListData.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.add(builderForValue.build());
          onChanged();
        } else {
          commandBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addCommand(
          int index, commandlist.data.protobuf.CommandListData.Command.Builder builderForValue) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.add(index, builderForValue.build());
          onChanged();
        } else {
          commandBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllCommand(
          java.lang.Iterable<? extends commandlist.data.protobuf.CommandListData.Command> values) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          super.addAll(values, command_);
          onChanged();
        } else {
          commandBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearCommand() {
        if (commandBuilder_ == null) {
          command_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          commandBuilder_.clear();
        }
        return this;
      }
      public Builder removeCommand(int index) {
        if (commandBuilder_ == null) {
          ensureCommandIsMutable();
          command_.remove(index);
          onChanged();
        } else {
          commandBuilder_.remove(index);
        }
        return this;
      }
      public commandlist.data.protobuf.CommandListData.Command.Builder getCommandBuilder(
          int index) {
        return getCommandFieldBuilder().getBuilder(index);
      }
      public commandlist.data.protobuf.CommandListData.CommandOrBuilder getCommandOrBuilder(
          int index) {
        if (commandBuilder_ == null) {
          return command_.get(index);  } else {
          return commandBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends commandlist.data.protobuf.CommandListData.CommandOrBuilder> 
           getCommandOrBuilderList() {
        if (commandBuilder_ != null) {
          return commandBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(command_);
        }
      }
      public commandlist.data.protobuf.CommandListData.Command.Builder addCommandBuilder() {
        return getCommandFieldBuilder().addBuilder(
            commandlist.data.protobuf.CommandListData.Command.getDefaultInstance());
      }
      public commandlist.data.protobuf.CommandListData.Command.Builder addCommandBuilder(
          int index) {
        return getCommandFieldBuilder().addBuilder(
            index, commandlist.data.protobuf.CommandListData.Command.getDefaultInstance());
      }
      public java.util.List<commandlist.data.protobuf.CommandListData.Command.Builder> 
           getCommandBuilderList() {
        return getCommandFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          commandlist.data.protobuf.CommandListData.Command, commandlist.data.protobuf.CommandListData.Command.Builder, commandlist.data.protobuf.CommandListData.CommandOrBuilder> 
          getCommandFieldBuilder() {
        if (commandBuilder_ == null) {
          commandBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              commandlist.data.protobuf.CommandListData.Command, commandlist.data.protobuf.CommandListData.Command.Builder, commandlist.data.protobuf.CommandListData.CommandOrBuilder>(
                  command_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          command_ = null;
        }
        return commandBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.oxseed.saas.archive.ocr.servlet.data.CommandList)
    }
    
    static {
      defaultInstance = new CommandList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.oxseed.saas.archive.ocr.servlet.data.CommandList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032Protobuf/commandlist.proto\022(com.oxseed" +
      ".saas.archive.ocr.servlet.data\"#\n\007Comman" +
      "d\022\n\n\002id\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\"Q\n\013CommandLi" +
      "st\022B\n\007command\030\001 \003(\01321.com.oxseed.saas.ar" +
      "chive.ocr.servlet.data.CommandB,\n\031comman" +
      "dlist.data.protobufB\017CommandListData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_Command_descriptor,
              new java.lang.String[] { "Id", "Name", },
              commandlist.data.protobuf.CommandListData.Command.class,
              commandlist.data.protobuf.CommandListData.Command.Builder.class);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_oxseed_saas_archive_ocr_servlet_data_CommandList_descriptor,
              new java.lang.String[] { "Command", },
              commandlist.data.protobuf.CommandListData.CommandList.class,
              commandlist.data.protobuf.CommandListData.CommandList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
